"""
chatbot_v2.py — Advanced Natural Language Data Analyst Assistant
Features:
- Dataset understanding (columns, types, summaries)
- Natural language → Pandas query conversion
- ✅ NEW: Execute pandas code generated by LLM
- ✅ NEW: Generate chart-ready JSON data for frontend
- ✅ NEW: Use full DataFrame instead of sample rows
- Automatic chart type suggestion
- Explainable insights
- Context-aware conversation (follow-up questions)
- Data quality warnings
- Suggested follow-up questions
- Safe query execution (no dangerous code)
"""

import os
import json
import re
import pandas as pd
import numpy as np
import google.generativeai as genai


# ── Safety: blocked keywords to prevent dangerous code execution ───────────────
BLOCKED_KEYWORDS = [
    "import os", "import sys", "subprocess", "eval(", "exec(",
    "open(", "__import__", "shutil", "rmdir", "remove(", "system(",
    "popen(", "shell=True", "pickle", "compile(", "globals()", "locals()"
]


class LLaMAChat:
    """
    Natural Language Data Analyst Assistant powered by Google Gemini.
    Class name kept as LLaMAChat to maintain compatibility with main.py.
    """

    def __init__(self):
        api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")

        if not api_key:
            raise ValueError(
                "GEMINI_API_KEY not found.\n"
                "Set it in your .env file:\n"
                "  GEMINI_API_KEY=your_key_here\n"
                "Get a key from: https://aistudio.google.com/app/apikey"
            )

        genai.configure(api_key=api_key)
        self.model = self._initialize_model()

        # Conversation history for context-aware follow-ups
        self.conversation_history = []
        self.last_query_result = None
        self.last_question = None

    def _initialize_model(self):
        """Auto-discover best available Gemini model."""
        preferred = [
            "models/gemini-1.5-flash",
            "models/gemini-1.5-pro",
            "models/gemini-pro",
        ]

        try:
            available = [
                m.name for m in genai.list_models()
                if "generateContent" in m.supported_generation_methods
            ]

            for name in preferred:
                if name in available:
                    print(f"✅ Using model: {name}")
                    return genai.GenerativeModel(
                        model_name=name,
                        generation_config={
                            "temperature": 0.3,
                            "top_p": 0.95,
                            "top_k": 40,
                            "max_output_tokens": 4096,
                        }
                    )

            if available:
                print(f"✅ Using fallback model: {available[0]}")
                return genai.GenerativeModel(
                    model_name=available[0],
                    generation_config={
                        "temperature": 0.3,
                        "top_p": 0.95,
                        "top_k": 40,
                        "max_output_tokens": 4096,
                    }
                )

            raise RuntimeError("No Gemini models available.")

        except Exception as e:
            raise RuntimeError(f"Model initialization failed: {str(e)}")

    # ════════════════════════════════════════════════════════════════════════
    # DATASET UNDERSTANDING
    # ════════════════════════════════════════════════════════════════════════

    def analyze_dataset(self, df: pd.DataFrame) -> dict:
        """
        Understand the dataset — detect columns, types, summaries.
        Called once when a dataset is uploaded.
        """
        analysis = {}

        analysis["columns"] = list(df.columns)
        analysis["shape"] = {"rows": int(df.shape[0]), "columns": int(df.shape[1])}

        analysis["column_types"] = {}
        for col in df.columns:
            if pd.api.types.is_numeric_dtype(df[col]):
                analysis["column_types"][col] = "numeric"
            elif pd.api.types.is_datetime64_any_dtype(df[col]):
                analysis["column_types"][col] = "date"
            else:
                sample = df[col].dropna().head(5).astype(str).tolist()
                if self._looks_like_date(sample):
                    analysis["column_types"][col] = "date"
                else:
                    analysis["column_types"][col] = "categorical"

        analysis["missing_values"] = {
            col: int(df[col].isnull().sum())
            for col in df.columns
            if df[col].isnull().sum() > 0
        }
        analysis["duplicate_rows"] = int(df.duplicated().sum())
        analysis["total_missing"] = int(df.isnull().sum().sum())

        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        if numeric_cols:
            analysis["numeric_summary"] = (
                df[numeric_cols].describe().round(2).to_dict()
            )

        cat_cols = [
            c for c, t in analysis["column_types"].items()
            if t == "categorical"
        ]
        analysis["categorical_summary"] = {}
        for col in cat_cols[:5]:
            analysis["categorical_summary"][col] = (
                df[col].value_counts().head(5).to_dict()
            )

        analysis["sample"] = df.head(3).replace({np.nan: None}).to_dict(orient="records")

        return analysis

    def _looks_like_date(self, samples: list) -> bool:
        """Heuristic check if string values look like dates."""
        date_patterns = [r"\d{4}-\d{2}-\d{2}", r"\d{2}/\d{2}/\d{4}", r"\d{2}-\d{2}-\d{4}"]
        for sample in samples:
            for pattern in date_patterns:
                if re.search(pattern, str(sample)):
                    return True
        return False

    # ════════════════════════════════════════════════════════════════════════
    # DATA QUALITY WARNINGS
    # ════════════════════════════════════════════════════════════════════════

    def get_data_quality_warnings(self, df: pd.DataFrame, question: str) -> list:
        """Warn user about data quality issues relevant to their question."""
        warnings = []

        q_lower = question.lower()
        for col in df.columns:
            if col.lower() in q_lower:
                missing = int(df[col].isnull().sum())
                if missing > 0:
                    pct = round((missing / len(df)) * 100, 1)
                    warnings.append(
                        f"⚠️ Column '{col}' has {missing} missing values ({pct}% of data)."
                    )

        total_missing = int(df.isnull().sum().sum())
        duplicates = int(df.duplicated().sum())

        if total_missing > 0 and not warnings:
            warnings.append(f"⚠️ Dataset has {total_missing} missing values across all columns.")
        if duplicates > 0:
            warnings.append(f"⚠️ Dataset has {duplicates} duplicate rows.")

        return warnings

    # ════════════════════════════════════════════════════════════════════════
    # CHART TYPE DETECTION
    # ════════════════════════════════════════════════════════════════════════

    def detect_chart_type(self, question: str) -> str:
        """Automatically detect what chart type fits the question."""
        q = question.lower()

        trend_keywords   = ["trend", "over time", "monthly", "weekly", "yearly", "by month", "by year", "timeline"]
        compare_keywords = ["compare", "comparison", "vs", "versus", "difference", "between", "top", "highest", "lowest", "best", "worst", "ranking"]
        dist_keywords    = ["distribution", "histogram", "spread", "range", "frequency"]
        prop_keywords    = ["proportion", "percentage", "share", "breakdown", "pie", "ratio", "composition"]

        if any(k in q for k in trend_keywords):
            return "line"
        elif any(k in q for k in prop_keywords):
            return "pie"
        elif any(k in q for k in dist_keywords):
            return "histogram"
        elif any(k in q for k in compare_keywords):
            return "bar"
        else:
            return "bar"

    # ════════════════════════════════════════════════════════════════════════
    # ✅ NEW FEATURE 2: CHART DATA GENERATOR
    # Converts pandas result into chart-ready JSON for Plotly / Chart.js
    # ════════════════════════════════════════════════════════════════════════

    def generate_chart_data(self, result, chart_type: str, question: str) -> dict:
        """
        Convert a pandas query result into chart-ready JSON.

        Rules:
        - Series  → index as x, values as y
        - DataFrame → first col as x, second col as y
        - Scalar → single_value type
        - ndarray → histogram bins

        Returns:
            {
                "chart": {
                    "type": "bar",
                    "x": [...],
                    "y": [...],
                    "title": "...",
                    "x_label": "...",
                    "y_label": "..."
                }
            }
        """
        try:
            title = question[:60] + "..." if len(question) > 60 else question

            # Case 1: pandas Series (most common — groupby result)
            if isinstance(result, pd.Series):
                result = result.dropna().head(20)
                return {
                    "chart": {
                        "type": chart_type,
                        "x": [str(i) for i in result.index.tolist()],
                        "y": [round(float(v), 2) if pd.notna(v) else 0 for v in result.values.tolist()],
                        "title": title,
                        "x_label": str(result.index.name or "Category"),
                        "y_label": str(result.name or "Value"),
                    }
                }

            # Case 2: pandas DataFrame
            elif isinstance(result, pd.DataFrame):
                result = result.head(20)
                cols = result.columns.tolist()
                x_col = cols[0]
                y_col = cols[1] if len(cols) >= 2 else cols[0]
                return {
                    "chart": {
                        "type": chart_type,
                        "x": [str(v) for v in result[x_col].tolist()],
                        "y": [round(float(v), 2) if pd.notna(v) else 0 for v in result[y_col].tolist()],
                        "title": title,
                        "x_label": x_col,
                        "y_label": y_col,
                    }
                }

            # Case 3: Single numeric value
            elif isinstance(result, (int, float, np.integer, np.floating)):
                return {
                    "chart": {
                        "type": "single_value",
                        "value": round(float(result), 2),
                        "title": title,
                    }
                }

            # Case 4: NumPy array → histogram
            elif isinstance(result, np.ndarray):
                arr = result[~np.isnan(result.astype(float))]
                counts, bin_edges = np.histogram(arr, bins=10)
                return {
                    "chart": {
                        "type": "histogram",
                        "x": [round(float(b), 2) for b in bin_edges[:-1]],
                        "y": [int(c) for c in counts],
                        "title": title,
                        "x_label": "Value",
                        "y_label": "Frequency",
                    }
                }

            else:
                return {"chart": None, "reason": "Result type not chartable"}

        except Exception as e:
            return {"chart": None, "reason": f"Chart generation error: {str(e)}"}

    # ════════════════════════════════════════════════════════════════════════
    # SAFE PANDAS QUERY EXECUTION
    # ════════════════════════════════════════════════════════════════════════

    def _is_safe_code(self, code: str) -> bool:
        """Security check — block dangerous code patterns."""
        code_lower = code.lower()
        for keyword in BLOCKED_KEYWORDS:
            if keyword.lower() in code_lower:
                return False
        return True

    def _extract_code(self, text: str) -> str:
        """Extract pandas code from LLM response (strips markdown fences)."""
        # Try ```python ... ``` block first
        match = re.search(r"```(?:python)?\n?(.*?)```", text, re.DOTALL)
        if match:
            code = match.group(1).strip()
            # Return first df line only
            for line in code.splitlines():
                line = line.strip()
                if line.startswith("df"):
                    return line
            return code.splitlines()[0] if code else ""

        # Try bare df lines
        lines = [l.strip() for l in text.strip().splitlines() if l.strip().startswith("df")]
        if lines:
            return lines[0]

        return ""

    def execute_pandas_query(self, df: pd.DataFrame, code: str):
        """
        Safely execute a pandas query string against the dataframe.
        Only df, pd, np are available in scope — no builtins allowed.
        """
        if not self._is_safe_code(code):
            raise ValueError("🚫 Unsafe code detected. Query blocked for security.")

        allowed_globals = {
            "df": df,
            "pd": pd,
            "np": np,
        }

        try:
            result = eval(code, {"__builtins__": {}}, allowed_globals)
            return result
        except Exception as e:
            raise ValueError(f"Query execution error: {str(e)}")

    # ════════════════════════════════════════════════════════════════════════
    # ✅ NEW FEATURE 1 HELPER: FORMAT RESULT PREVIEW
    # Converts pandas result to readable markdown table (max 10 rows)
    # ════════════════════════════════════════════════════════════════════════

    def _format_result_preview(self, result) -> str:
        """Format pandas query result as markdown table, max 10 rows."""
        try:
            if isinstance(result, pd.DataFrame):
                preview = result.head(10)
                try:
                    table = preview.to_markdown(index=True)
                except Exception:
                    table = preview.to_string(index=True)
                return f"\n📊 **Result Preview:**\n{table}\n"

            elif isinstance(result, pd.Series):
                preview = result.head(10).reset_index()
                preview.columns = [str(c) for c in preview.columns]
                try:
                    table = preview.to_markdown(index=False)
                except Exception:
                    table = preview.to_string(index=False)
                return f"\n📊 **Result Preview:**\n{table}\n"

            elif isinstance(result, (int, float, np.integer, np.floating)):
                return f"\n📊 **Result:** `{round(float(result), 4)}`\n"

            elif isinstance(result, (list, dict)):
                return f"\n📊 **Result:**\n```\n{str(result)[:500]}\n```\n"

            else:
                return f"\n📊 **Result:** `{str(result)[:300]}`\n"

        except Exception as e:
            return f"\n⚠️ Could not format result preview: {str(e)}\n"

    # ════════════════════════════════════════════════════════════════════════
    # SUGGESTED FOLLOW-UP QUESTIONS
    # ════════════════════════════════════════════════════════════════════════

    def _get_followup_suggestions(self, df: pd.DataFrame, question: str) -> list:
        """Generate smart follow-up question suggestions based on dataset columns."""
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        cat_cols = df.select_dtypes(include=["object"]).columns.tolist()

        suggestions = []

        if numeric_cols and cat_cols:
            suggestions.append(f"Compare {numeric_cols[0]} by {cat_cols[0]}")
        if len(numeric_cols) >= 2:
            suggestions.append(f"What is the correlation between {numeric_cols[0]} and {numeric_cols[1]}?")
        if cat_cols:
            suggestions.append(f"Show top 5 {cat_cols[0]} by {numeric_cols[0] if numeric_cols else 'count'}")

        date_cols = [c for c in df.columns if "date" in c.lower() or "month" in c.lower() or "year" in c.lower()]
        if date_cols and numeric_cols:
            suggestions.append(f"Show monthly trend of {numeric_cols[0]}")

        suggestions.append("Show data quality summary")
        suggestions.append("What are the top insights from this dataset?")

        return suggestions[:4]

    # ════════════════════════════════════════════════════════════════════════
    # MAIN RESPONSE GENERATOR
    # ════════════════════════════════════════════════════════════════════════

    def generate_response(self, user_question: str, context: dict) -> str:
        """
        Main entry point called by main.py.

        UPGRADE SUMMARY:
        1. Uses context["df"] (full DataFrame) instead of rebuilding from samples
        2. Executes the pandas code returned by LLM and shows result preview
        3. Generates chart-ready JSON data for the frontend
        """
        try:
            # ── ✅ UPGRADE 3: Use full DataFrame ──────────────────────────
            # main.py should pass context["df"] = full_dataframe
            # Fallback to sample_data if full df is not passed
            df = context.get("df")

            if df is None:
                sample = context.get("sample_data")
                if sample:
                    try:
                        df = pd.DataFrame(sample)
                        print("⚠️ Warning: Using sample data — pass context['df'] for accurate analysis.")
                    except Exception:
                        df = None

            # ── Data Quality Warnings ──────────────────────────────────────
            warnings_text = ""
            if df is not None:
                warnings = self.get_data_quality_warnings(df, user_question)
                if warnings:
                    warnings_text = "\n".join(warnings) + "\n\n"

            # ── Chart Type Detection ───────────────────────────────────────
            chart_type = self.detect_chart_type(user_question)
            chart_hint = f"📊 Suggested chart type: **{chart_type.upper()}** chart\n\n"

            # ── Conversation History ───────────────────────────────────────
            history_text = ""
            if self.conversation_history:
                recent = self.conversation_history[-3:]
                history_text = "RECENT CONVERSATION:\n"
                for exchange in recent:
                    history_text += f"User: {exchange['question']}\nAssistant: {exchange['answer'][:200]}...\n\n"

            # ── Dataset Context for LLM ────────────────────────────────────
            dataset_info = f"""
DATASET INFORMATION:
- Shape: {context.get('shape', 'Unknown')}
- Columns: {', '.join(context.get('columns', []))}
- Data Types: {json.dumps(context.get('dtypes', {}), default=str)}
- Missing Values: {json.dumps(context.get('missing_values', {}), default=str)}

STATISTICAL SUMMARY:
{json.dumps(context.get('summary', {}), indent=2, default=str)[:2000]}

SAMPLE DATA (first 3 rows):
{json.dumps(context.get('sample_data', {}), indent=2, default=str)[:1500]}
"""

            # ── LLM Prompt ─────────────────────────────────────────────────
            prompt = f"""You are a friendly, expert AI Data Analyst helping non-technical users understand their data.

{history_text}

{dataset_info}

USER QUESTION: {user_question}

INSTRUCTIONS:
1. Answer the question CLEARLY and DIRECTLY in plain English
2. Provide ONE SINGLE executable pandas code snippet that answers the question
   - Must start with "df." 
   - Use ONLY column names from the dataset above
   - Wrap in ```python ``` block
   - Example: df.groupby("product")["sales"].sum().sort_values(ascending=False).head(10)
3. Give a clear EXPLANATION of how the answer was calculated
4. Highlight KEY NUMBERS in **bold**
5. Use bullet points for lists
6. End with: "💡 INSIGHT:" followed by one key takeaway

RESPONSE FORMAT:
📌 **Answer:** [Direct answer]

📊 **Analysis:**
[Explanation]

```python
[one line pandas code]
```

💡 **Insight:** [Key takeaway]
"""

            # ── Call Gemini API ────────────────────────────────────────────
            response = self.model.generate_content(prompt)

            if not response or not response.text:
                return "⚠️ No response generated. Please try rephrasing your question."

            answer_text = response.text

            # ── ✅ UPGRADE 1: Extract & Execute Pandas Code ────────────────
            result_preview_text = ""
            chart_data = {"chart": None}

            if df is not None:
                extracted_code = self._extract_code(answer_text)

                if extracted_code:
                    try:
                        # Execute the code safely
                        executed_result = self.execute_pandas_query(df, extracted_code)
                        self.last_query_result = executed_result

                        # Format result as markdown table
                        result_preview_text = self._format_result_preview(executed_result)

                        # ── ✅ UPGRADE 2: Generate Chart Data ──────────────
                        chart_data = self.generate_chart_data(
                            executed_result, chart_type, user_question
                        )

                    except ValueError as ve:
                        result_preview_text = (
                            f"\n⚠️ Could not execute generated query. Showing explanation only.\n"
                            f"_{str(ve)}_\n"
                        )
                    except Exception:
                        result_preview_text = (
                            "\n⚠️ Could not execute generated query. Showing explanation only.\n"
                        )
                else:
                    result_preview_text = (
                        "\n⚠️ No executable pandas code found in response. Showing explanation only.\n"
                    )

            # ── Suggested Follow-ups ───────────────────────────────────────
            if df is not None:
                followups = self._get_followup_suggestions(df, user_question)
            else:
                followups = [
                    "Show top 5 records",
                    "What are the missing values?",
                    "Show summary statistics",
                    "Compare columns",
                ]

            followup_text = "\n\n---\n🔍 **Suggested follow-up questions:**\n"
            for i, q in enumerate(followups, 1):
                followup_text += f"{i}. {q}\n"

            # ── Chart JSON for frontend ────────────────────────────────────
            chart_text = ""
            if chart_data.get("chart"):
                chart_text = (
                    "\n\n---\n📈 **Chart Data (JSON for frontend):**\n"
                    f"```json\n{json.dumps(chart_data, indent=2, default=str)}\n```\n"
                )

            # ── Save conversation history ──────────────────────────────────
            self.conversation_history.append({
                "question": user_question,
                "answer": answer_text,
            })
            if len(self.conversation_history) > 10:
                self.conversation_history = self.conversation_history[-10:]

            # ── Build Final Response ───────────────────────────────────────
            full_response = (
                warnings_text
                + chart_hint
                + answer_text
                + result_preview_text
                + chart_text
                + followup_text
            )

            return full_response

        except Exception as e:
            error_msg = str(e)

            if "404" in error_msg:
                return "❌ **Model not found.**\n\nCheck your API key: https://aistudio.google.com/app/apikey"
            elif "quota" in error_msg.lower():
                return "❌ **API quota exceeded.**\n\nCheck: https://console.cloud.google.com/"
            elif "invalid" in error_msg.lower() and "key" in error_msg.lower():
                return "❌ **Invalid API key.**\n\nUpdate GEMINI_API_KEY in your .env file."
            else:
                return (
                    f"❌ **Error:** {error_msg}\n\n"
                    "**Try:**\n"
                    "1. Check your API key in .env\n"
                    "2. Verify internet connection\n"
                    "3. Rephrase your question\n"
                    "4. Restart the backend"
                )

    def clear_history(self):
        """Reset conversation history (new session)."""
        self.conversation_history = []
        self.last_query_result = None
        self.last_question = None 